<?php
/**
 * This file is automatically generated from Chatwing API
 * @author chatwing
 */
return array(
    'user/chatbox/list' => array(
        'type' => 'get',
        'auth' => true
    ),
    'chatbox/read' => array(
        'type' => 'get',
        'auth' => true
    )
);